/usr/bin/env cpan Algorithm::Permute
/usr/bin/env cpan Bio::DB::Sam
/usr/bin/env cpan DBI
/usr/bin/env cpan DBD::SQLite
/usr/bin/env cpan Digest::MD5 
/usr/bin/env cpan File::Slurp
/usr/bin/env cpan Getopt::Long::Descriptive
/usr/bin/env cpan IO::Prompt
/usr/bin/env cpan List::MoreUtils
/usr/bin/env cpan LWP::Simple
/usr/bin/env cpan Math::Round
/usr/bin/env cpan Module::Build
/usr/bin/env cpan Moose
/usr/bin/env cpan Parallel::ForkManager
/usr/bin/env cpan Pod::Usage
/usr/bin/env cpan Regexp::Common
/usr/bin/env cpan Smart::Comments
/usr/bin/env cpan Statistics::Basic
/usr/bin/env cpan Statistics::KernelEstimation
/usr/bin/env cpan System::Wrapper
/usr/bin/env cpan Test::Exception
/usr/bin/env cpan Test::More
