cpan Algorithm::Permute
cpan Bio::DB::Sam
cpan DBI
cpan DBD::SQLite
cpan Digest::MD5 
cpan File::Slurp
cpan Getopt::Long::Descriptive
cpan IO::Prompt
cpan List::MoreUtils
cpan LWP::Simple
cpan Math::Round
cpan Module::Build
cpan Moose
cpan Parallel::ForkManager
cpan Pod::Usage
cpan Regexp::Common
cpan Smart::Comments
cpan Statistics::Basic
cpan Statistics::KernelEstimation
cpan System::Wrapper
cpan Test::Exception
cpan Test::More
