
=head1 dzlab.pmb.berkeley.edu/tools README

L<http://dzlab.pmb.berkeley.edu/tools/archive>

This page contains everything you need to know to get the Zilberman Lab scripts running on your computer.  

=head2 Overview

You need to install packages in order to get the scripts running on your computer: DZ-Perl and DZLab-Tools.  DZ-Perl is
a customized version of Perl.  DZLab-Tools contains the actual scripts.  

=head2 Installing DZ-Perl and DZLab-Tools

Both DZ-Perl and DZLab-Tools are available from L<http://dzlab.pmb.berkeley.edu/tools/archive>.  Simply download the
most recent version of each, for example dzlab-tools-0.0.6.exe and dz-perl-1.2.exe, and double click each to install.
The order of installation does not (or at least shouldn't) matter.

The packages are installed to c:\dzlab-tools and c:\dz-perl, though you shouldn't need to know that.

=head2 Upgrading

Simply grab the latest version of DZLab-Tools (and DZ-Perl, if there's a newer version of that as well) from
L<http://dzlab.pmb.berkeley.edu/tools/archive> and double click the installer.  The older version will be automatically
uninstalled.  (Note: You can also downgrade by installing an older version.)

=head2 Launching the command line

The command line can be launched from the Start Menu, via Start Menu->All Programs->Zilberman Lab->DZLab Command Line.
From this command line, you should be able launch all scripts installed in c:\dzlab-tools directly (without 'perl -S'),
from any directory.  For example:

=for html <img src="launch.jpg">

Be sure to check out the new console windows settings (Edit->Settings) to adjust font sizes/etc.  

=head2 On Linux

Install Git.  For ubuntu:

 sudo apt-get install git-core 

Install bowtie by downloading from bowtie-bio.sourceforge.net, extracting the directory and running 'make'.

Checkout the dzlab-tools bundle:

 git clone git://dzlab.pmb.berkeley.edu/dzlab-tools

Make sure to set the PATH variable correctly by pointing it to the directories with dzlab-tools and bowtie.  On bash
(default on ubuntu and most linux distros), put this in your ~/.profile or ~/.bash_profile:

 export PATH=/path/to/dzlab-tools:/path/to/bowtie:$PATH

You may have to log out and back in to see the effects of this. 

=cut
